name: meg-m2-rnaseq-r-2024
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.1.3
  - r-essentials=4.1
  - r-tidyverse=1.3.1
  - r-magrittr=2.0.1
  - r-matrixstats=0.61.0
  - r-ggplot2=3.3.5
  - r-ggfortify=0.4.14
  - r-ggrepel=0.9.1
  - r-rcolorbrewer=1.1_2
  - r-stringr=1.4.0
  - r-corrplot=0.92
  - r-factominer=2.4
  - r-factoextra=1.0.7
  - r-ggnewscale=0.4.7
  - r-wgcna=1.71
  - r-flashclust=1.01_2
  - r-data.table=1.14.2
  - bioconductor-biocmanager=1.30.16
  - bioconductor-deseq2=1.34.0
  - bioconductor-vsn=3.62.0
  - bioconductor-affy=1.72.0
  - bioconductor-complexheatmap=2.10.0
  - bioconductor-org.mm.eg.db=3.14.0
  - bioconductor-clusterprofiler=4.2.2
  - bioconductor-enrichplot=1.14.2
  - bioconductor-reactomepa=1.38.0
