name: meg_m1-ue5-unix2
# 2025 - UE A2B - partie I du pipeline RNAseq
# depuis template repo RNAseq_Plasma 
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  # Jupyter dependencies
  - jupyterhub>=1.5,<2
  - jupyterlab>=3.2,<4
  - jupyter-resource-usage
  - jupyterlab-topbar
  - jupyterlab-topbar-text
  - jupyterlab-system-monitor
  - nodejs
  # Jupyter archive
  # https://github.com/jupyterlab-contrib/jupyter-archive
  - jupyter-archive
  # Bash environment
  - python>=3.8
  - pip
  - pip:
    - bash_kernel
   # For the M1 A2B course:
  - fastqc=0.12.1
  - multiqc=1.13
  - fastp=0.23.1
  - star=2.7.11a
  - samtools=1.18
  - bc=1.07.1
  - qualimap=2.2.2b
  - subread=2.0.6
  #- pip:
  #  - jupyter
  #  - notebook
  #  - nbconvert
